import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  safeV: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    flex: 1,
    marginBottom: 60,
  },
  bannerV: {
    backgroundColor: '#FF4510',
    borderRadius: 15,
    marginRight: 10,
  },
  header: {
    flexDirection: 'row',
    marginTop: 10,
  },
  cardImg: {
    marginTop: 10,
    marginLeft: 25,
    width: 100,
    height: 90,
    borderRadius: 15,
  },
  cardTextName: {
    marginTop: 5,
    fontWeight: 'bold',
    fontSize: 18,
    marginLeft: 30,
    color: 'black',
  },
  cardTextPrice: {
    marginTop: 1,
    fontWeight: 'bold',
    fontSize: 18,
    color: 'black',
    marginLeft: 40,
  },
  cardTextPrice1:{
    fontWeight: 'bold',
    fontSize: 18,
    color: 'black',
    marginLeft: 20,
  },
  increViewContainer: {
    marginTop: 7,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  textAddCart: {
    color: 'black',
    fontSize: 15,
    fontWeight: 'bold',
  },
  cardV2: {
    flexDirection: 'row',
    marginBottom: 10,
  },
  txtBanner: {
    marginTop: 15,
    fontWeight: 'bold',
    fontSize: 15,
    color: 'black',
  },
  txtB2: {
    marginTop: 20,
    fontWeight: 'bold',
    fontSize: 15,
    color: 'black',
  },
  card: {
    height: 40,
    marginLeft: 30,
    alignItems: 'flex-end',
    justifyContent: 'space-evenly',
    width: 230,
    marginHorizontal: 2,
    borderRadius: 10,
    marginBottom: 20,
    padding: 15,
  },

  Banners: {
    flexDirection: 'row',
  },
  shadow: {
    shadowColor: '#202020',
    shadowOffset: {width: 0, height: 0},
    shadowRadius: 5,
  },
  categoryContainer: {
    flexDirection: 'row',
    marginTop: 5,
    marginBottom: 10,
    justifyContent: 'space-between',
    marginLeft: 10,
    alignItems: 'center',
    opacity: 2,
  },
  categoryText: {
    fontSize: 16,
    color: 'black',
    fontWeight: 'bold',
    justifyContent: 'center',
    alignItems: 'center',
  },
  categoryTextSelected: {
    color: '#FF9800',
    paddingBottom: 10,
    borderBottomWidth: 3,
    borderColor: '#FF9800',
    justifyContent: 'center',
    alignItems: 'center',
  },
  card2: {
    padding: 7,
    width: 175,
    height: 250,
  },
  txtR: {
    marginTop: 10,
    marginBottom: 10,
    fontFamily: 'GILROY-REGULAR',
    fontSize: 18,
    fontWeight: 'bold',
    color: 'black',
  },
  txtP: {
    marginTop: 10,
    marginBottom: 10,
    fontWeight: 'bold',
    color: 'black',
  },
  cardV: {
    backgroundColor: '#ffff',
    marginRight: 10,
    borderRadius: 15,
  },
  cardCategory: {
    backgroundColor: '#ffff',

    height: 240,
    width: 170,
    borderRadius: 15,
  },
  btnTouchable: {
    alignItems: 'center',
    height: 25,
    width: 25,
    backgroundColor: '#A9A9A9',
    borderRadius: 5,
    justifyContent: 'center',
    marginRight: 15,
  },
  btnTouchable1: {
    alignItems: 'center',
    height: 25,
    width: 25,
    backgroundColor: '#FFD700',
    borderRadius: 5,
    justifyContent: 'center',
    marginLeft: 15,
  },
  txt: {
    fontWeight: 'bold',
    fontSize: 15,
    color: 'black',
  },
  txt1: {
    fontWeight: 'bold',
    fontSize: 15,
    color: 'black',
  },
  touchableAdd: {
    padding: 5,
    height: 30,
    width: 130,
    marginTop: 2,
    marginLeft: 20,
    borderRadius: 15,
    alignItems: 'center',
  },
});

export default styles;
